platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/tas_ppe/cve-scanner
    tag: 0.0.6-beta

inputs:
  - name: concourse-cve-scan
  - name: tas-cve 
  - name: target-bosh-release

run:
  path: concourse-cve-scan/tasks/scan/scan.sh