resources:
- name: uaa-git
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/uaa
- name: grype
  type: github-release
  source: 
    uri: git@github.com:anchore/grype.git
    tag: v0.65.1

jobs:
- name: scan-uaa-with-grype
  plan:
  - get: uaa-git
  - get: grype
  - task: do-a-thing
    config:
      platform: linux
      run:
        path: echo
        args: ["Hello world!"]