---
resources:
  - name: cve-scan
    type: git
    source:
      uri: git@github.com:rhall-pivotal/concourse-cve-scan.git
      branch: develop
      private_key: ((cve_scan.private_key))
  - name: tas-cve
    type: github-release
    source:
      access_token: ((cve_scan.github_access_token))
      repository: tas-cve
      user: pivotal
  - name: capi-release
    type: git
    source:
      uri: git@github.com:cloudfoundry/capi-release.git
      branch: 1.156.0 
      private_key: ((cve_scan.private_key))

jobs:
  - name: syft-and-grype
    serial: true
    plan:
      - in_parallel:
          - get: cve-scan
          - get: capi-release
          - get: tas-cve
      - task: run-scan
        file: cve-scan/tasks/scan/scan.yml
        input_mapping:
          cve-scan-repo: cve-scan
        params:
          TARGET_REPO: capi-release
          RELEASE_VERSION: pre-release-test
          RELEASE_NAME: capi
          GRYPE_FAILURE_LEVEL: none
          DRY_RUN: true
