---
resources:
  - name: concourse-cve-scan
    type: git
    source:
      uri: git@github.com:rhall-pivotal/concourse-cve-scan.git
      branch: main
      private_key: ((cve_scan.private_key))
  - name: tas-cve
    type: github-release
    source:
      access_token: ((cve_scan.github_access_token))
      repository: tas-cve
      user: pivotal
  - name: target-bosh-release
    type: git
    source:
      uri: git@github.com:cloudfoundry/credhub-cli.git
      branch: main
      private_key: ((cve_scan.private_key))

jobs:
  - name: scan-with-syft-and-grype
    serial: true
    plan:
      - in_parallel:
          - get: concourse-cve-scan
          - get: tas-cve
          - get: target-bosh-release
      - task: run-scan
        file: concourse-cve-scan/tasks/scan/scan.yml
        params:
          DRY_RUN: false
          GRYPE_FAILURE_LEVEL: high
          RELEASE_NAME: credhub-cli
          RELEASE_VERSION: pre-release-cve-scan
