---
resources:
  - name: cve-scan
    type: git
    source:
      uri: git@github.com:rhall-pivotal/concourse-cve-scan.git
      branch: develop
      private_key: ((cve_scan.private_key))
  - name: tas-cve
    type: github-release
    source:
      access_token: ((cve_scan.github_access_token))
      repository: tas-cve
      user: pivotal
#Currently on the image
  # - name: grype-cli
  #   type: github-release
  #   source:
  #     access_token: ((cve_scan.github_access_token)) 
  #     owner: anchore
  #     repository: grype
#Param this into the jorbs
  - name: capi-release
    type: github-release
    source:
      access_token: ((cve_scan.github_access_token))
      owner: cloudfoundry
      repository: capi-release
      version: { tag: '1.156.0'}

jobs:
  - name: scan-release-with-grype
    serial: true
    plan:
      - in_parallel:
          - get: cve-scan
          - get: capi-release
          - get: grype-cli 
          - get: tas-cve
      - task: run-scan
        file: cve-scan/tasks/scan/scan.yml
        input_mapping:
          cve-scan-repo: cve-scan