---
resources:
  - name: tas-cve
    type: github-release
    source:
      access_token: ((cve_scan.github_access_token))
      repository: tas-cve
      user: pivotal
  - name: grype-cli
    type: github-release
    source: 
      owner: anchore
      repository: grype
  - name: uaa-release
    type: github-release
    source:
      owner: cloudfoundry
      repository: uaa-release
  - name: cve-scan
    type: git
    source:
      uri: git@github.com:rhall-pivotal/concourse-cve-scan.git
      branch: main
      private_key: ((cve_scan.github_access_token))

jobs:
  - name: scan-release-with-grype
    serial: true
    plan:
      - in_parallel:
          - get: cve-scan
          - get: uaa-release
          - get: grype-cli 
          - get: tas-cve
      - task: run-scan
        file: cve-scan/tasks/yml/scan.yml