---
#! ******************************************
#! Secrets you will need to run this pipeline
#! ******************************************
github_token: &github_token ((cve_scan.github_access_token))
  #! github_token is needed so the pipeline can access the tas-cve cli for uploading to dependency-track. We recommend generating from your team github account. You'll want to use any token that can access your github release.
git_key: &git_key ((cve_scan.private_key)
  #! git_key is needed so the pipeline can clone the git repos for the tasks needed and the repo to be scanned.  We recommend generating from your team github account. If you want to run tasks directly from this repo, contact @ryanhall to ask for creds.
#! **************
#! End of secrets
#! **************

resources:
  - name: concourse-cve-scan
    type: git
    source:
      uri: git@github.com:rhall-pivotal/concourse-cve-scan.git
      branch: main
      private_key: *git_key
  - name: tas-cve
    type: github-release
    source:
      access_token: *github_token
      repository: tas-cve
      user: pivotal
  - name: target-bosh-release
    type: git
    source:
      uri: git@github.com:cloudfoundry/credhub-cli.git
      branch: main
      private_key: *git_key
jobs:
  - name: scan-with-syft-and-grype
    serial: true
    plan:
      - in_parallel:
          - get: concourse-cve-scan
          - get: tas-cve
          - get: target-bosh-release
      - task: run-scan
        file: concourse-cve-scan/tasks/scan/scan.yml
        params:
          DRY_RUN: false
          GRYPE_FAILURE_LEVEL: high
          RELEASE_NAME: credhub-cli
          RELEASE_VERSION: pre-release-cve-scan
